### PR TITLE
Add a `stack` accessor

### LINKED ISSUE #11: Add a `stack` accessor?
ie, `stack :: Error -> String`, that just reads the `stack` property. There's no agreed-upon format but [according to MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/stack) all modern browsers support it, and I'm pretty sure it's always a String.

### PR DESCRIPTION
**Pull request by hdgarrood**
Resolves #11. While I was at it, I couldn't resist correcting "Javascript" to "JavaScript", sorry ;)

### CODE REVIEW

**Comment by paf31** [comment]
:+1: Looks good to me.

**Comment by hdgarrood** [comment]
(nudge)

**Comment by hdgarrood** [comment]
Thank you :)

**Comment by garyb** [comment]
Sorry about the delay!

**Pull request merged**
