### PR TITLE
adds a try function

### PR DESCRIPTION
**Pull request by kRITZCREEK**
turns exceptions into Eithers, adresses #15

### CODE REVIEW

**Comment by paf31** [comment]
👍

**Comment by kRITZCREEK** [comment]
Just as a question. Do we prefer unicode arrows, forall and double colon in libraries?

**Comment by garyb** [comment]
I've been avoiding them, as with the core libraries being one place newcomers are likely to encounter PS code, I don't want to scare them off with "crazy symbols" or something.

**Comment by kRITZCREEK** [comment]
Sounds good, I can empathize with that.

**Pull request merged**
