### PR TITLE
Added Discard instance

### PR DESCRIPTION
**Pull request by Risto-Stevcev**

### CODE REVIEW

**Comment by paf31** [comment]
I don't think errors should be discardable.

**Comment by Risto-Stevcev** [comment]
liftEff and launchAff get used often enough, and those values are worth ignoring a lot of the time. For `liftEff`, if it has a type signature like `Either Error Unit`, I don't see an issue with discarding that

**Comment by paf31** [comment]
I think encouraging users to discard errors like this would be a bad thing.

**Comment by Risto-Stevcev** [comment]
They would still be able to discard it using `_ <-`. Isn't the `Discard` class and instances (or lack thereof) just avoiding the extra boilerplate? What would it be stopping people from doing that they can't already do?

**Comment by paf31** [comment]
The point of `Discard` is to force users to acknowledge that they are discarding something which is non-trivial. `Error` is non-trivial, so users should be forced to acknowledge it. In fact, it's sort of the perfect example of what `Discard` is for 😄

**Comment by Risto-Stevcev** [comment]
> The point of Discard is to force users to acknowledge that they are discarding something which is non-trivial

I guess I just don't understand what this is accomplishing. Doesn't this only benefit people who are new to purescript and don't understand that every line in a do block returns a value?

Everyone who's familiar with do notation knows that if they write `foo bar` in a do block, that it's equivalent to `_ <- foo bar`, and not having a `Discard` instance doesn't prevent someone from writing `_ <-` instead of `whatever <-`

**Comment by paf31** [comment]
> Doesn't this only benefit people who are new to purescript and don't understand that every line in a do block returns a value?

No, I've had bugs recently which were caused by my forgetting to use a value returned in a `do` block.

**Comment by paf31** [comment]
Also, if you think `Discard` is not accomplishing anything, then we should discuss it on the compiler issue tracker. It seems like `Error` is an arbitrary choice in that case.

**Comment by garyb** [comment]
> No, I've had bugs recently which were caused by my forgetting to use a value returned in a do block.

Likewise, that's why it was proposed in the first place - GHC warns about it too for similar reasoning.

:-1: from to this from me I'm afraid!

**Comment by Risto-Stevcev** [comment]
Huh, that's interesting. I've never ran into an issue with that, but you guys have way more experience coding in purescript than me. Ok I guess if it's a :-1:  I'll go ahead and close this PR

**Comment by garyb** [comment]
There's an example of the kind of place it can occur in https://github.com/purescript/purescript/issues/1803#issue-125645079 - due to a use of `<$>` rather than a `=<<` in that case. It's not super common, but I have done it (or things like it) several time, it's tricky to track down why an effect is not occurring :)

**Pull request closed without merging**
